// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzfbXptJGMR0ekRwKy3cDj8krfIHqd-tw',
    appId: '1:1054940532703:web:f0d938ec5b5a789ebc7e6a',
    messagingSenderId: '1054940532703',
    projectId: 'todo-14775',
    authDomain: 'todo-14775.firebaseapp.com',
    storageBucket: 'todo-14775.appspot.com',
    measurementId: 'G-5GS1KSDDQQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-f9cIFNQ2rmNciHTmORzNbn0XZ22dd9Q',
    appId: '1:1054940532703:android:a458454b589b4cfdbc7e6a',
    messagingSenderId: '1054940532703',
    projectId: 'todo-14775',
    storageBucket: 'todo-14775.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdYCOe9SlrHGW8cmxMl9bt1YDz50gJJUA',
    appId: '1:1054940532703:ios:0d7e10cdb76a1abfbc7e6a',
    messagingSenderId: '1054940532703',
    projectId: 'todo-14775',
    storageBucket: 'todo-14775.appspot.com',
    iosBundleId: 'com.example.todofirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAzfbXptJGMR0ekRwKy3cDj8krfIHqd-tw',
    appId: '1:1054940532703:web:ee7fdc9fc23ccd0fbc7e6a',
    messagingSenderId: '1054940532703',
    projectId: 'todo-14775',
    authDomain: 'todo-14775.firebaseapp.com',
    storageBucket: 'todo-14775.appspot.com',
    measurementId: 'G-RVLVLW2SDY',
  );

}